### PR TITLE
CTB review day2

### PR DESCRIPTION
**Pull request by ctb**
Went through day 2 materials, minor fixes etc.

### CODE REVIEW

**Comment by ctb** [comment]
@brooksph @halexand I think ready for review. Some aspects still not dealt with, but it all runs in my hands.

**Comment by ctb** [comment]
One question for @brooksph - do we want to slap in the intro to k-mers at the top of the sourmash compare page? I can do that if it seems like a good idea.

And what other things were we thinking of doing for sourmash?

**Comment by brooksph** [comment]
@ctb yes, please do. I meant to add that in there. I am putting together a gather tutorial with the three Hu et al read datasets. I'm running them through gather now and was going compare the output with an upset plot. Please add some other cool sourmash stuff.

**Comment by ctb** [comment]
ok!!

go ahead and merge this first, if you like.

On Mon, Sep 25, 2017 at 03:52:33PM +0000, Phillip Brooks wrote:
> @ctb yes, please do. I meant to add that in there. I am putting together a gather tutorial with the three Hu et al read datasets. I'm running them through gather now and was going compare the output with an upset plot. Please add some other cool sourmash stuff. 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ngs-docs/2017-cicese-metagenomics/pull/4#issuecomment-331925794
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Review by brooksph — COMMENTED** [review]
LGTM

**Pull request merged**
